name: myenvatd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - opencv
  - pytorch-cuda=11.8
  - torchvision
  - tensorboard
  - pip:
      - dlib
      - tensorboardx
      - protobuf